export const theme = {
  light: {
    background: '#ffffff',
    foreground: '#0f172a',
    card: '#ffffff',
    'card-foreground': '#0f172a',
    popover: '#ffffff',
    'popover-foreground': '#0f172a',
    primary: '#2563eb',
    'primary-foreground': '#ffffff',
    secondary: '#f1f5f9',
    'secondary-foreground': '#0f172a',
    muted: '#f1f5f9',
    'muted-foreground': '#64748b',
    accent: '#f1f5f9',
    'accent-foreground': '#0f172a',
    destructive: '#ef4444',
    'destructive-foreground': '#ffffff',
    border: '#e2e8f0',
    input: '#e2e8f0',
    ring: '#2563eb',
  },
  dark: {
    background: '#0f172a',
    foreground: '#f8fafc',
    card: '#1e293b',
    'card-foreground': '#f8fafc',
    popover: '#1e293b',
    'popover-foreground': '#f8fafc',
    primary: '#3b82f6',
    'primary-foreground': '#ffffff',
    secondary: '#334155',
    'secondary-foreground': '#f8fafc',
    muted: '#334155',
    'muted-foreground': '#94a3b8',
    accent: '#334155',
    'accent-foreground': '#f8fafc',
    destructive: '#ef4444',
    'destructive-foreground': '#ffffff',
    border: '#334155',
    input: '#334155',
    ring: '#3b82f6',
  },
}

export const getTheme = (mode = 'light') => theme[mode]
